# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubreeUser',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usertype', models.TextField(max_length=6)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('contact', models.TextField()),
                ('pincode', models.TextField()),
                ('gender', models.TextField()),
                ('verificationstatus', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
    ]
