# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubreeuser',
            name='password',
            field=models.TextField(default=datetime.datetime(2016, 4, 23, 13, 41, 15, 522000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
