# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_hubreeuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hubreeuser',
            old_name='gender',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='hubreeuser',
            name='usertype',
        ),
    ]
